dist: xenial
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y wget libwxgtk3.0-dev libgtk2.0-dev gettext autopoint libasound2-dev alsa-utils alsa-oss
    - git show -s --format="#define REV_LONG \"%H\"%n#define REV_TIME \"%cd\"%n" | tee ./src/RevisionIdent.h
    - g++ --version
    - wget https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-Linux-x86_64.sh
    - sh cmake-3.17.2-Linux-x86_64.sh --skip-license
language:
    - cpp
script:
    - mkdir build
    - cd build
    - time ../bin/cmake .. && time make -j2
